name: Generate CODEOWNERS
on:
  push:
    paths:
      - '**/CODEOWNERS'

jobs:
  generate-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install codeowners-generator
        run: |
          npm install -g codeowners-generator
      - name: Verify installation
        run: which codeowners-generator 

      - name: Generate CODEOWNERS file
        run: |
          codeowners-generator generate
      - name: Commit and push CODEOWNERS file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:

