name: Generate CODEOWNERS

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install codeowners-generator
        run: |
          npm install -g codeowners-generator
      - name: Verify installation
        run: which codeowners-generator 
    
      - name: Generate CODEOWNERS file
        run: |
          codeowners-generator generate

      - name: Commit and push CODEOWNERS file
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate CODEOWNERS file"
